# Generated by Django 4.1.5 on 2023-03-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_course_education_eligibility_gender_scholarship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='gender',
        ),
    ]
