# Generated by Django 4.1.5 on 2023-03-24 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_remove_scholarship_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='host',
            field=models.ForeignKey(default='aveesah', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='last_date',
            field=models.DateField(),
        ),
    ]
