# Generated by Django 4.1.5 on 2023-03-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_scholarship_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='location',
        ),
    ]
