# Generated by Django 4.1.5 on 2023-03-24 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_location_remove_scholarship_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='location',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location'),
        ),
    ]
