# Generated by Django 4.1.5 on 2023-03-24 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_scholarship_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='last_date',
            field=models.DateField(default=django.db.models.deletion.SET_NULL),
        ),
    ]
