# Generated by Django 4.1.5 on 2023-03-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_scholarship_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='education',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='education',
            field=models.ManyToManyField(to='accounts.education'),
        ),
    ]
