# Generated by Django 4.1.5 on 2023-03-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_scholarship_education_scholarship_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='education',
        ),
    ]
