# Generated by Django 4.1.5 on 2023-03-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_scholarship_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='degrees',
            field=models.ManyToManyField(to='accounts.education'),
        ),
    ]
