# Generated by Django 4.1.5 on 2023-03-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_scholarship_degrees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='degrees',
            new_name='education',
        ),
    ]
