# Generated by Django 4.1.5 on 2023-03-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_scholarship_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='education',
        ),
    ]
