# Generated by Django 4.1.5 on 2023-03-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_scholarship_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
