# Generated by Django 4.1.5 on 2023-03-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='education',
            field=models.ManyToManyField(to='accounts.education'),
        ),
    ]
