# Generated by Django 4.1.5 on 2023-03-24 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0018_scholarship_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='host',
            field=models.ForeignKey(default='admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
