# Generated by Django 4.1.5 on 2023-03-27 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_scholarship_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Living_Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='education',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='award',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='course',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='last_date',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='name',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='amt_accomodation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='amt_living',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='org_tuition',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='per_sch',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='to_be_paid_tuition',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='tuition_covered',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='uni_name',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='accomodation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.accomodation'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.key'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.language'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='living',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.living_expense'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.major'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.month'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.year'),
        ),
    ]
