# Generated by Django 4.1.5 on 2023-03-30 22:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_accomodation_key_language_living_expense_major_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='s_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField(default='admin', null=True)),
                ('uni_name', models.TextField(max_length=250, null=True)),
                ('major', models.TextField(null=True)),
                ('key', models.TextField(null=True, verbose_name=accounts.models.Key)),
                ('level', models.CharField(max_length=12)),
                ('language', models.TextField(null=True)),
                ('tuition_covered', models.FloatField(max_length=10, null=True)),
                ('accomodation', models.CharField(max_length=3, null=True)),
                ('living', models.CharField(max_length=3, null=True)),
                ('to_be_paid_tuition', models.FloatField(max_length=10, null=True)),
                ('per_sch', models.FloatField(max_length=100, null=True)),
                ('org_tuition', models.FloatField(max_length=10, null=True)),
                ('month', models.IntegerField(null=True, verbose_name=accounts.models.Month)),
                ('year', models.IntegerField(null=True, verbose_name=accounts.models.Year)),
                ('amt_accomodation', models.FloatField(null=True)),
                ('amt_living', models.FloatField(null=True)),
            ],
        ),
    ]
