# Generated by Django 4.1.5 on 2023-03-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_s_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_data',
            name='key',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='s_data',
            name='month',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='s_data',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
