# Generated by Django 4.1.5 on 2023-03-30 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_s_data_key_alter_s_data_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='level',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.education'),
        ),
    ]
